# Core Network Parameters (Pivoted to Local Node)
stratum_port: ":5555"
kaspad_address: "127.0.0.1:16110"

# Central Pool Wallet
mining_address: "kaspa:qql2vwejyye7rcp39fdr7n0jfk2vlpvrkt2ke49ztsxceduw4hyw6ld9ts5yv"

# Public Pool Mechanics
starting_diff: 64       # ⚡ Allows IceRiver and Goldshell miners to survive
min_share_diff: 2.0      
var_diff: true           
shares_per_min: 20
extranonce_size: 2

# Telemetry System
prom_port: ":8081"
print_stats: true