# Core Network Parameters (Pivoted to Local Node)
stratum_port: ":5555"
kaspad_address: "127.0.0.1:16110"

# Central Pool Wallet (Matched to Master Admin Treasury)
mining_address: "kaspa:qrc3ezl770p2cjlfc3tjp6vqlldt6lgh3e80d6rm4rchtt0yrrpgzqave8579"

# Public Pool Mechanics
starting_diff: 64       # ⚡ Allows IceRiver and Goldshell miners to survive
min_share_diff: 2.0      
var_diff: true           
shares_per_min: 20
extranonce_size: 2

# Telemetry System
prom_port: ":8081"
print_stats: true